### ISSUE TITLE
Circle-ci explanation is incorrect in readme

### ISSUE THREAD

**Issue by dlasalle** [BytePackager/packagecore#112]
Should be
```
machine:
  services:
    - docker
...
deployment:
  package:
    tag: /^v.*$/
    commands:
      - sudo apt-get update -qy
      - sudo apt-get install -qy python3 python3-pip libyaml-dev
      - sudo python3 -m pip install packagecore
      - packagecore -o "${CIRCLE_ARTIFACTS}" "${CIRCLE_TAG#v}"
```
